apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: db-lumen
type: Opaque
data:
  master_root_user: cm9vdAo=
  master_root_password: cm9vdAo=
  db_user: c2ltcGxlCg==
  db_password: c2ltcGxlCg==
  master_username: bG9raQo=
  master_password: bG9raV8xMjMK
  replication_username: dXNlcgo=
  replication_password: cGFzc3dvcmQK