apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNVEEyTWpBeApPRFU0TWpaYUZ3MDBNVEEyTWpBeE9EVTRNalphTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDZmc3ZUdvQkV0QzM1OERrTXdCQ01UVithaVp3QmZ3M2k3aUoxZ3ZtQ2V6MEh4QzErWgp0MWpLYnZHaGlwTDNhNVl1akhUNWF2RkJFZjJqS1l4K05FaUZCOTN3WXU4blVWSVdmemhyTVkvaCtXNHM5MGxqClZKbDRKL2tGR21VM2dxSnI4dXFvYkVYSXdZVnF0MDZKZEU1QlJiam1kZ0NOUU9STHZDSWJFUXdTS1RNZTZDeEUKMGc5WkRsUUxTK0hxV0xCQlFHdHNrUEo3a0xTTkcvY1drd01rbUw4Qm1GWmdyTVhBQzJjUk1rcG4vWlQzUG5tWApDT0h2M3dTNHBMQzdWRGRRS296TS90VWtsTHBHR0ExYnZDRHR4ZCtORTBBWGU2dWpVcDhoZUttc210RGxydVdICi9TQzQvaEV1c2htRVlDOVltVFV6Qk4zVWhZemdVQkRuK0ZOVEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlJISUNXYVhFSHhwMVNNVXVNSQpxVjNpbTI4V2dEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFOUW9vVGVrUXk1ZTRGUWQyZGxnZmhrTEozcStOClhQMUxUcldsN3lpbmE3QmY4YWlTYWVTLzBxNjFPREtxSk91ZGxTR3JZUWk2Y2VlMVRuOWFzb0pZZXpqbkh6U1IKMWNabk5HREt2RkErYWpjQlpiaW04MHp1c0dLN1pFaGZlQ0VrMExaUFpxS0Q0ejA0ZndNR0pLdUxzclcwOWpQTwpPc2VZTll0Wjg1eEhhWWErMmJnbmUvTnMvYktrS1RTV0gzUW5xREhTb3ZoakRYNGNCQTl3UXVkUlU5SnZpa3ViCnV3MnRvZmFGZEQrVTVreWdYOXUyVWRPMDJYMzNEcHppdUpHNnE5anhnZmtMU2hyYkYyNlF4VWQ4aVR2ZmE0QlQKczdKSmZVb2U5RUJhY2o3eHQrU29rZWZtMlV6bHJpRzZDT3pUWVNjQTVGM3hxZDE1MXpwaUh3OVJLdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://e96b5972-9a2b-4221-bd3c-6988dd1c2d08.k8s.ondigitalocean.com
  name: do-fra1-k8s-general-testing
contexts:
- context:
    cluster: do-fra1-k8s-general-testing
    user: do-fra1-k8s-general-testing-admin
  name: do-fra1-k8s-general-testing
current-context: do-fra1-k8s-general-testing
kind: Config
preferences: {}
users:
- name: do-fra1-k8s-general-testing-admin
  user:
    token: d080769bfcb4d3dc7914349cf5f4e74645dadd04054c8d35661b3f066e9d6b7c
