apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
  namespace: auth-lumen
  labels:
    pv: local
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  hostPath:
    path: /data/pv0001/
