apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-lumen
  namespace: auth-lumen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-lumen
  template:
    metadata:
      labels:
        app: auth-lumen
    spec:
      volumes:
        - name: code
          persistentVolumeClaim:
            claimName: code
      containers:
      - name: auth-lumen
        image: docker.pkg.github.com/mike-prog-lab/auth-tasks-lumen/auth-tl-php-fpm:1.2.1-dev
        env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: auth-lumen-configmap
              key: app_name
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: auth-lumen-secret
              key: key
        - name: DB_CONNECTION
          valueFrom:
            configMapKeyRef:
              name: auth-lumen-configmap
              key: db_connection
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-configmap
              key: port
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-configmap
              key: host
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: db-configmap
              key: db_name
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        # volumeMounts:
        #   - name: code
        #     mountPath: /var/www/html
        #     subPath: code
        ports:
        - containerPort: 9000
      initContainers:
        - name: init-systcl
          image: busybox
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: code
              mountPath: /var/www/html
              subPath: code
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: auth-lumen-service
  namespace: auth-lumen
  labels:
    tier: backend
spec:
  selector:
    app: auth-lumen
    tier: backend
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
