apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code
  namespace: auth-lumen
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  selector:
    matchLabels:
      pv: local